#!/usr/bin/env sh
set -ex

exec 2>&1

COMMAND=/usr/local/bin/consul-template
PID_FILE=/run/nginx/consul-template.pid

if [ -n "${CONSUL_ADDR}" ]; then
    # Create pid file's directory
	install -d -o nginx -g nginx ${PID_FILE%/*}
	# Check consule-template command is executable or not
	test -x ${COMMAND} || exit 0
	# Run consul-template
	exec ${COMMAND} -consul-addr=${CONSUL_ADDR} -config=/etc/consul.cfg -pid-file=${PID_FILE}
fi

